Add most populars films
desyatov-student/filmorate pull request #12
Opened 2024-08-08 10:31 UTC by ongonets

2024-08-08 19:32 UTC, desyatov-student requested changes

2024-08-08 19:32 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<FilmDto> getPopular(Long count, Long genryId, Long year) {
Опечатка genryId -> genreId

2024-08-08 19:32 UTC, desyatov-student commented on src/test/java/ru/yandex/practicum/filmorate/dal/FilmDbStorageTests.java
> +    public void testFindPopularFilms() {
Тест должен проверять какой то один кейс. Давай разобьем на несколько. 
Например:
testGetPopular_Return2Films_GenreIsNullAndYearIsNull()

testGetPopular_Return2Films_YearIsNull()

и тд

структура теста:

// Given
Подготовка данных
// When
Вызываем метод
// Then
Проверяем результат

2024-08-08 19:32 UTC, desyatov-student commented on src/test/resources/test-data.sql
> +    ('testFilm','testDescription', '2020-11-23',150, 1);
Может названия разные сделать ?

2024-08-11 06:50 UTC, desyatov-student approved these changes
На будущее: разделять тест на такую структуру, это позволяет лучше его читать:

// Given
Подготовка данных
// When
Вызываем метод
// Then
Проверяем результат

2024-08-11 10:46 UTC, DanilkaZanin approved these changes

2024-08-11 11:09 UTC, merged