Add common films
desyatov-student/filmorate pull request #13
Opened 2024-08-08 12:39 UTC by ongonets

2024-08-08 19:42 UTC, desyatov-student requested changes

2024-08-08 19:42 UTC, desyatov-student commented on src/test/java/ru/yandex/practicum/filmorate/dal/FilmDbStorageTests.java
> +    public void testFindCommonFilms() {
Вопрос по неймингу: НазваниеМетода_чтовернет_когда.
 
Скорее всего нужно разбить на 2 теста. Второй тест после действия лайк

структура теста:

// Given
Подготовка данных
// When
Вызываем метод
// Then
Проверяем результат

2024-08-08 19:42 UTC, desyatov-student commented on src/test/resources/application.properties
> +# ? jdbc-url ???????, ??? ?????? ????? ????????? ? ????
с кодировкой что-то не то

2024-08-10 12:52 UTC, DanilkaZanin commented on src/test/resources/application.properties
> +# ? jdbc-url ???????, ??? ?????? ????? ????????? ? ????
у меня после клонирования репозитория такая-же штука

2024-08-10 17:06 UTC, desyatov-student commented on src/test/resources/application.properties
> +# ? jdbc-url ???????, ??? ?????? ????? ????????? ? ????
Проверь настройку. Ты же создавал этот файл. клонирование не влияет:
![image](https://github.com/user-attachments/assets/6823cf5e-9068-44b8-b536-81adf842d0eb)

2024-08-11 17:26 UTC, StanislavFishkov reviewed
Мне кажется проверку на существование пользователей стоит добавить перед запросом общих фильмов, иначе при некорректном запросе нам просто вернется пустой список вместо ошибки.

2024-08-11 17:26 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    }
Мне кажется, тут надо добавить проверки на существование пользователей перед запросом.

2024-08-11 17:26 UTC, StanislavFishkov commented on src/test/java/ru/yandex/practicum/filmorate/dal/FilmDbStorageTests.java
> +        assertThat(films.stream().findFirst())
Тут можно для наглядности использовать из AssertJ .hasSize() в первой строчке, и .first().isPresent().get() во второй.

2024-08-11 19:41 UTC, StanislavFishkov approved these changes

2024-08-11 20:25 UTC, desyatov-student approved these changes

2024-08-11 20:25 UTC, merged