Add reviews
desyatov-student/filmorate pull request #14
Opened 2024-08-09 21:49 UTC by desyatov-student

2024-08-11 18:09 UTC, StanislavFishkov requested changes

2024-08-11 18:09 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ReviewDto getGenreById(@PathVariable Long id) {
getGenreById - забыл переименовать метод похоже.

2024-08-11 18:09 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private final UserService userService;
Так получается высокая связанность разных сервисов. Сервисы должны зависеть только от DAL, но не от соседних сервисов. Во всяком случае, так наставники отвечали на вопросы по данной теме.

2024-08-11 18:09 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void remove(Review review);
void remove(Review review);
boolean removeRate(Review review, Long userId);

Какая все-таки логика - методы remove возвращают ответ или нет? Это и в других местах было, я запутался какой концепции придерживаемся.

2024-08-11 18:09 UTC, StanislavFishkov commented on src/test/java/ru/yandex/practicum/filmorate/dal/ReviewDbStorageTests.java
> +    public void testLikeReview_returnReviewsOrderedByUseful_Review2Like3TimesAndDislike1TimeAndReview1Like1Time() {
Не уверен, что такое название теста упрощает, а не усложняет понимание, что он делает. Может, если хочется подробно описать, то использовать "@DisplayName", чтобы можно было описать суть на более понятном языке. Это касательно третьей части названия. Как предложение.

2024-08-11 18:30 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private final UserService userService;
меня тоже этот вопрос волновал. В этой реализации проще то что не нужно обрабатывать если не найден пользователь все будет в другом сервисе и он кинет ошибку

2024-08-11 18:33 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private final UserService userService;
Зачем ты так сделал, я понял, но это прямо явно было обозначено как плохая практика наставниками. В пачке, насколько я помню, было обсуждение. И в одном из видео с наставником, кажется.

2024-08-11 18:34 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void remove(Review review);
с помощь boolean хотел решать задачу кидать ошибку если не найдено, чтобы не искать сначала, но потом что то забил на это

2024-08-11 18:52 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void remove(Review review);
Добавил

2024-08-11 18:52 UTC, desyatov-student commented on src/test/java/ru/yandex/practicum/filmorate/dal/ReviewDbStorageTests.java
> +    public void testLikeReview_returnReviewsOrderedByUseful_Review2Like3TimesAndDislike1TimeAndReview1Like1Time() {
добавил описание

2024-08-11 18:53 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ReviewDto getGenreById(@PathVariable Long id) {
переименовал

2024-08-11 18:56 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void remove(Review review);
убрал

2024-08-11 19:30 UTC, StanislavFishkov submitted a review, later dismissed

2024-08-12 07:41 UTC, StanislavFishkov approved these changes, later dismissed

2024-08-12 11:05 UTC, ongonets commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        }
Стоит перенести эту логику в слой сервисов

2024-08-12 11:17 UTC, ongonets commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        return getById(reviewId);
Двойное обращение к БД,  стоит возвращать ранее созданный объект

2024-08-12 11:17 UTC, ongonets commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        return getById(reviewId);
То же самое

2024-08-12 11:17 UTC, ongonets commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        return getById(reviewId);
И еще

2024-08-12 11:36 UTC, ongonets commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        return getById(reviewId);
Двойное обращение к БД, стоит возвращать ранее созданный объект

2024-08-12 11:38 UTC, ongonets commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        User user = userService.getUserById(userId);
Необходима проверка на наличие оценки отзыва

2024-08-12 11:54 UTC, ongonets commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.removeRate(review, user.getId());
Проверку наличия отзыва и юзера будет лучше заменить на проверку наличия оценки отзыва пользователем, так как первые проверки  не гарантирует её наличие, возможна ошибка

2024-08-12 12:03 UTC, ongonets reviewed
Лучше будет перенести работу с оценками отзывов в отдельный репозиторий и имплементировать его в сервис, тогда решится проблема с ReviewRateRowMapper.

2024-08-12 18:38 UTC, Maks333 submitted a review, later dismissed

2024-08-12 21:16 UTC, StanislavFishkov submitted a review, later dismissed

2024-08-13 00:01 UTC, StanislavFishkov approved these changes

2024-08-13 04:32 UTC, ongonets approved these changes

2024-08-13 04:34 UTC, merged