Add search
desyatov-student/filmorate pull request #15
Opened 2024-08-11 12:54 UTC by Maks333

2024-08-11 14:16 UTC, desyatov-student requested changes

2024-08-11 14:16 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        String director = modes.contains(SearchMode.DIRECTOR) ? query.toLowerCase() : "VALUE_FOR_UNSELECTED_SEARCH_MODE";
Может быть сделать составной SQL чтобы при отсутствии параметра не делать проверку по какой то рандомной строке ?

2024-08-11 14:16 UTC, desyatov-student commented on src/test/java/ru/yandex/practicum/filmorate/service/AddSearchTests.java
> +public class AddSearchTests {
Если это тесты на базу давай их перенесем в FilmDbStorageTests и сервис здесь не используем
Если нужно протестировать Сервис то базу нужно замокать. Можно посмотреть примеры тестов в сервисах
Тесты нужно разделить по слоям
Название класса + Tests

2024-08-11 19:06 UTC, StanislavFishkov requested changes

2024-08-11 19:06 UTC, StanislavFishkov commented on src/test/java/ru/yandex/practicum/filmorate/service/AddSearchTests.java
> +@Sql(value = "/add-search/clear.sql", executionPhase = Sql.ExecutionPhase.AFTER_TEST_CLASS)
Вопрос: правильно ли дропать таблицы в данном случае. Если схема основная поменяется, то тесты будут продолжать работать, как ни в чем не бывало, потому что они на своей схеме по сути живут. Предлагаю просто очистить все строчки в соответствующих таблицах и создать нужные значения. Все это, мне кажется, можно сделать в одном файле.

А зачем нужно дропать таблицы после класса?

2024-08-11 19:06 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        String director = modes.contains(SearchMode.DIRECTOR) ? query.toLowerCase() : "VALUE_FOR_UNSELECTED_SEARCH_MODE";
Мне тоже показался подход не обычным. Ты его сам придумал или где-то взял? Интересно.

При этом все работает, даже если в базе будет именно такое словосочетание, так как проверки выполняются по нижнему регистру. Но мне почему-то хотелось бы, как минимум, чтобы это на уровне Storage было, чтобы сервис не решал какую строку использовать, если отбор по одному из полей не интересует.

2024-08-12 15:30 UTC, StanislavFishkov requested changes

2024-08-12 15:30 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/error/handling/ErrorHandler.java
> +    }
Надо логирование тут добавить, как в остальных обработчиках ошибок. Также желательно проанализировать exception и сообщение выдавать в зависимости от того, что в exception. Если в дальнейшем сюда может упасть иная ошибка, чем из-за поиска, то сообщение станет неинформативным.

2024-08-12 21:19 UTC, StanislavFishkov approved these changes

2024-08-12 21:36 UTC, desyatov-student approved these changes

2024-08-12 21:36 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +        if (query.isEmpty() || query.isBlank()) {
достаточно query.isBlank()

2024-08-12 21:36 UTC, merged