Add director
desyatov-student/filmorate pull request #16
Opened 2024-08-11 16:43 UTC by StanislavFishkov

2024-08-11 19:33 UTC, ongonets commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            ARRAY_AGG(DISTINCT ARRAY[CAST(g.ID AS varchar), g.NAME] ORDER BY g.ID) FILTER (WHERE g.ID IS NOT NULL) AS genres
В SQL выражении нет запроса списка режиссеров

2024-08-11 19:37 UTC, ongonets commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            ARRAY_AGG(DISTINCT g.NAME) AS genre_names,
Столбцы genre_ids и genre_names возможно убрать

2024-08-11 19:39 UTC, ongonets commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            ARRAY_AGG(DISTINCT ARRAY[CAST(g.ID AS varchar), g.NAME] ORDER BY g.ID) FILTER (WHERE g.ID IS NOT NULL) AS genres
Также добавить запрос списка режиссеров

2024-08-11 19:50 UTC, ongonets reviewed
Проблему дубликации жанров, лайков, режиссеров необходимо решить на уровне БД, в данный момент она не решена.
По добавленной функциональности все хорошо, за исключением пары комментариев

2024-08-11 19:59 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            ARRAY_AGG(DISTINCT ARRAY[CAST(g.ID AS varchar), g.NAME] ORDER BY g.ID) FILTER (WHERE g.ID IS NOT NULL) AS genres
Спасибо! это я криво объединился, видимо. Исправил.

2024-08-11 19:59 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            ARRAY_AGG(DISTINCT g.NAME) AS genre_names,
Исправил.

2024-08-11 19:59 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            ARRAY_AGG(DISTINCT ARRAY[CAST(g.ID AS varchar), g.NAME] ORDER BY g.ID) FILTER (WHERE g.ID IS NOT NULL) AS genres
Добавил.

2024-08-11 20:10 UTC, desyatov-student requested changes

2024-08-11 20:10 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public List<DirectorDto> getUsers() {
Может getDirectors ? Смутил вызов контроллере. Разные методы

2024-08-11 20:10 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (directorId == null) {
Можно в модели UpdateDirectorRequest навесить @NotNull для id

2024-08-11 20:10 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            default: throw new ValidationException("Director's films might be sorted only by \"likes\" or \"year\"");
Может sortBy мапить в enum и сюда передавать?
Тогда ошибку можно отсюда вынести куда-нибудь в бизнес слой (сервис)

2024-08-11 20:10 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dal/mappers/FilmRowMapper.java
> +                Object[] directorFields = (Object[]) resultSetGenres.getArray("Value").getArray();
круто что получилось в объект запихать 👍

2024-08-11 20:10 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dal/mappers/FilmRowMapper.java
> +                Object[] directorFields = (Object[]) resultSetGenres.getArray("Value").getArray();
название переменной только надо изменить на genreFields

2024-08-11 20:10 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dto/UpdateDirectorRequest.java
> +    @NotNull
@NotBlank проверят на null, поэтому @NotNull можно убрать и в других местах тоже

2024-08-11 20:10 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@EqualsAndHashCode(of = {"id"})
Лучше убрать проверку только по id.
Например в тестах при обновлении модели имя поменяется и они не должны быть равными а по факту будут потому что id  у них одинаковый

2024-08-11 20:10 UTC, desyatov-student commented on src/main/resources/schema.sql
> +    director_id BIGINT REFERENCES directors (id) ON DELETE CASCADE
стоит добавить для  film_id  director_id - NOT NULL
Я в прошлых скриптах упустил этот момент и можно добавить несуществующий фильм

2024-08-11 20:10 UTC, desyatov-student commented on src/test/java/ru/yandex/practicum/filmorate/dal/DirectorDbStorageTest.java
> +        // test-data.sql
👍

2024-08-11 20:10 UTC, desyatov-student commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTests.java
> +    private DirectorStorage directorStorage;
Не используется

2024-08-11 20:14 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public List<DirectorDto> getUsers() {
Да, опечатка. Спасибо, исправил.

2024-08-11 20:17 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/mappers/FilmRowMapper.java
> +                Object[] directorFields = (Object[]) resultSetGenres.getArray("Value").getArray();
Блин, тоже опечатка. Исправил.

Ага, но я помучился, если честно)

2024-08-11 20:18 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/dto/UpdateDirectorRequest.java
> +    @NotNull
Убрал. Была мысль, что лишнее.

2024-08-11 20:19 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@EqualsAndHashCode(of = {"id"})
Мы же используем usingRecursiveComparison(), чтобы проверялось по всем полям. А по бизнес-логике - два директора с одним id, это один режиссер. Разве нет?

2024-08-11 20:21 UTC, StanislavFishkov commented on src/main/resources/schema.sql
> +    director_id BIGINT REFERENCES directors (id) ON DELETE CASCADE
Согласен, добавил.

2024-08-11 20:24 UTC, StanislavFishkov commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTests.java
> +    private DirectorStorage directorStorage;
Без него не поднимется FilmService, так как там зависимость. Я добавил, потому что ошибка выдалась при компилляции.

2024-08-11 20:43 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@EqualsAndHashCode(of = {"id"})
👌

2024-08-11 21:13 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            default: throw new ValidationException("Director's films might be sorted only by \"likes\" or \"year\"");
Переданное значение проверяю через @Pattern(regexp = "year|likes") на уровне контроллера. Тут для чистоты эксперимента добавил.

Переделал на Enum.

2024-08-11 21:41 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (directorId == null) {
Предлагаю пока оставить так. После мерджей приведем к единому виду.

2024-08-12 04:31 UTC, ongonets approved these changes

2024-08-12 04:53 UTC, desyatov-student approved these changes

2024-08-12 04:57 UTC, merged