Add feed
desyatov-student/filmorate pull request #17
Opened 2024-08-12 11:01 UTC by DanilkaZanin

2024-08-12 15:58 UTC, StanislavFishkov requested changes

2024-08-12 15:58 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/dto/FeedDto.java
> +    private String operation;
Оба поля должны быть Enum.

2024-08-12 15:58 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +    private String operation;
Оба поля должны быть Enum.

2024-08-12 15:58 UTC, StanislavFishkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FeedStorage.java
> +    void save(FeedDto feedDto);
Должен возвращать сам себя (Feed), как в остальных storage при сохранении

2024-08-12 15:58 UTC, StanislavFishkov commented on src/main/resources/schema.sql
> +    timestamp BIGINT,
Почему BIGINT, а не TIMESTAMP?

2024-08-12 15:58 UTC, StanislavFishkov commented on src/main/resources/schema.sql
> +    timestamp BIGINT,
ещё можно сделать так, чтобы метка заполнялась автоматом на уровне БД:
DEFAULT now()
https://dba.stackexchange.com/questions/107475/how-to-best-store-a-timestamp-in-postgresql

2024-08-12 15:58 UTC, StanislavFishkov commented on src/test/java/ru/yandex/practicum/filmorate/dal/FeedDbStorageTests.java
> +        assertThat(feeds.size()).isEqualTo(2);
можно написать так: assertThat(feeds).hasSize(2);

2024-08-12 15:58 UTC, StanislavFishkov commented on src/test/java/ru/yandex/practicum/filmorate/dal/FeedDbStorageTests.java
> +    }
А зачем готовить данные для одного конкретного теста в @BeforeEach? Надо перенести в сам тест. И добавить ещё хотя бы один тест, где удаление и добавление лайка тестируется.

2024-08-13 05:21 UTC, desyatov-student requested changes

2024-08-13 05:21 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                new FeedDto(
В репозитории работаем только с Feed
FeedDto - выдаем наружу

2024-08-13 05:21 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                new FeedDto(
Так же предложение дублируйщее создание `new Feed()` вынести в какую то сущность (я за то чтобы это был `FeedService`) с методом:
```Java
feedService.create(userId, eventType, operation, entityId)
```
и там будет вся дублирующая логика

2024-08-13 10:00 UTC, desyatov-student requested changes

2024-08-13 10:00 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        feedDbStorage.save(feedService.create(userId, EventType.LIKE, Operation.REMOVE, id));
feedService.create(userId, EventType.LIKE, Operation.REMOVE, id)

2024-08-13 10:00 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +        return new Feed(
Сохранить в БД 
feedDbStorage.save()

2024-08-13 12:52 UTC, desyatov-student approved these changes, later dismissed

2024-08-13 15:59 UTC, StanislavFishkov requested changes

2024-08-13 15:59 UTC, StanislavFishkov commented on src/main/resources/script.json
Скрипт postman надо убрать.

2024-08-13 15:59 UTC, StanislavFishkov commented on src/test/java/ru/yandex/practicum/filmorate/dal/FeedDbStorageTests.java
> +                Instant.now().toEpochMilli(),
Если я все правильно понял, то для сохранения TIMESTAMP по текущему стандарту jdbc можно передавать напрямую класс offsetDateTime. Тогда код тут стоит сделать такой offsetDateTime.now(). Это не замечание, а предложение)

2024-08-13 16:06 UTC, desyatov-student approved these changes

2024-08-13 16:08 UTC, StanislavFishkov approved these changes

2024-08-13 16:09 UTC, merged