Team's Project
desyatov-student/filmorate pull request #22
Opened 2024-08-13 17:17 UTC by desyatov-student

2024-08-14 09:33 UTC, tomattman requested changes
Привет, прекрасная работа, в основном по комментариям моменты на улучшение, и повышение консистентной

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam(defaultValue = "year") @Pattern(regexp = "year|likes") String sortBy
вместо того чтобы использовать паттерн на валидацию, можно было бы сделать enum с возможными значениями, и принимать его в параметре

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam(defaultValue = "year") @Pattern(regexp = "year|likes") String sortBy
а enum уже есть  
два минуса у этого похода, прийдется принимать значения в upperCase и если значение будет не из енама будет другая ошибка

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/converter/StringToEnumConverter.java
> +public class StringToEnumConverter implements Converter<String, SearchMode> {
не очень понятно, зачем нужен этот класс, если единственный метод просто вызывает другой метод

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/converter/StringToEnumConverter.java
> +public class StringToEnumConverter implements Converter<String, SearchMode> {
ну или если его используете, то почему там где я комментировал приходит строка а не enum

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseDbStorage.java
> +    protected <S> Optional<S> findOne(String query, RowMapper<S> mapper, Object... params) {
оставлю коммент здесь, но относится он к классу
можно было бы сделать еще интереснее
1) сделать класс абстрактным (чтобы нельзя было создать его объект
2) добавить абстрактные методы, которые возвращают строку с запросом для этих методов
3) в классе наследнике переопределить эти методы, чтобы возвращать соответствующие запросы
и тогда во всех классах наследниках будут этим методы работающие автоматически, и надо будет только переопределить метод готовящий запрос (т.е. вместо константы, возвращать эту же строку из метода)
(методы, для того, чтобы использующий не забыл переопределить метод)

Но это делать не обязательно, просто как интересное улучшение

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/dto/review/NewReviewRequest.java
> +package ru.yandex.practicum.filmorate.dto.review;
для ревью дто вынесены в отдельный пакет, для фильмов или режиссеров нет, выглядит не очень консистентно

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/dto/review/UpdateReviewRequest.java
> +    Long id;
модификатор доступа

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/model/SortOrderFilmsByDirector.java
> +    public static SortOrderFilmsByDirector from(String order) {
снова не консистентно, где то это делается в самом enum где то в отдельных конвертерах, где то методе просто

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    private final DirectorMapper directorMapper = new DirectorMapperImpl();
на мапперы мапстракта можно повесить аннотацию, чтобы они создавались как спринг бины, и инжектались как и другие компоненты

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    private Director getDirectorById(Long directorId, String errorMessage) {
снова больше как небольшое улучшение, 
сообщение скорее всего всегда будет одинаковое поэтому можно убрать сообщение из параметров и в нем оставить константой

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    private Director getDirectorById(Long directorId, String errorMessage) {
да и везде используется метод без сообщения

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +    void setUserService(@Lazy UserService userService) {
модификатор доступа

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +    void setUserService(@Lazy UserService userService) {
и зачем делать его ленивым?

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +    void setUserService(@Lazy UserService userService) {
учитывая что все методы его используют, то смысла в этом нету

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +    void setUserService(@Lazy UserService userService) {
Если это попытка избежать циклической зависимости, то лучше вообще ее избежать
Лучше завязаться на репозиторий пользователей, учитывая что нам оттуда надо только получение по идентификатору
Ну или второй вариант, так как все эти методы нуждаются в пользователе, то проксировать эти запросы через юзер сервис, в юзер сервисе создать методы createFeed и getFeeds он проверяет существование пользователя, и если пользователь существует, уже тогда, вызывает эти методы

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private final FilmService filmService;
тут снова про потенциальные циклические зависимости, так как эти сервисы нам нужны только для проверки существования объектов, можно изжектить репозитории и  тут уже делать методы, на получение из репозитория

2024-08-14 09:33 UTC, tomattman commented on src/main/java/ru/yandex/practicum/filmorate/storage/FeedStorage.java
> +package ru.yandex.practicum.filmorate.storage;
слегка неудобно что интерфейсы и их реализации лежат отдельно, чаще всего в пакет с интерфейсами кладут пакет, в котором лежат реализации, а если есть несколько типов реализаций, то под каждый тип отдельный подпакет

2024-08-14 10:12 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +    void setUserService(@Lazy UserService userService) {
Для того чтобы уйти от циклических ссылок. Подключать репозиторий не хочется потому что в сервисе есть логика проверки и кидания ошибки , придется здесь дублировать это

2024-08-14 15:57 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private final FilmService filmService;
Написал в личку по этому вопросу. Предложение оставить так

2024-08-15 11:35 UTC, tomattman approved these changes
Принято

2024-08-22 19:26 UTC, merged