Implement database
desyatov-student/filmorate pull request #7
Opened 2024-07-05 18:24 UTC by desyatov-student

2024-07-09 09:28 UTC, TomattmanYandex requested changes
Привет, не хватает картинки со схемой базы данных
и надо больше тестов

2024-07-09 09:28 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +    private static final String FIND_ALL_QUERY = """
Если этот запрос используется только в одном месте, зачем его выносить в константы, почему бы не оставить его на уровне метода?

2024-07-09 09:28 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            ARRAY_AGG(DISTINCT g.ID) AS genre_ids,
интересное решение, минусом которого будет то, что может потеряться связь между идентификатором жанра и исменем жанра

2024-07-09 09:28 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dto/UpdateFilmRequest.java
> +public class UpdateFilmRequest {
а почему тут валидации нету получается что при апдейте все правила другие?

2024-07-09 09:28 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dto/UpdateUserRequest.java
> +    private Long id;
и тут

2024-07-09 09:28 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        removeGenreDuplicates(film);
для удаления дубликатов можно было использовать set вместо list Set сам по себе не поддерживает дубликаты

2024-07-09 09:28 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/mappers/FilmMapper.java
> +    FilmDto toFilmDto(Film film);
Тут просто про удобство
Если методы в мапперах называть toDto и toEntity то прийдется меньше заморачиваться, так как тип сущности есть в имени класса а дальше задумываешься только о том, в дто или в сущность базы надо мапить

2024-07-09 09:28 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
эти реализации можно удалить уже (даже нужно)

2024-07-09 11:21 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            ARRAY_AGG(DISTINCT g.ID) AS genre_ids,
да я понимаю. такая проблема есть если встречаются дубликаты. Открыт к предложениям. В идеале нужно вернуть объект.

2024-07-09 11:22 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +    private static final String FIND_ALL_QUERY = """
В тех примера которые мы делали на курсе всегда выносили в константы. Мне кажется так код чище  и в методах нет этих тестов

2024-07-09 11:23 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dto/UpdateFilmRequest.java
> +public class UpdateFilmRequest {
Тут вопрос открытый как сделать. Потому что при обновлении полей может не быть совсем. И тогда надо какие то кастомные аннотации делать чтобы проверять если есть значение то тогда валидировать;

2024-07-09 11:25 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        removeGenreDuplicates(film);
Я использовал обычный сет но тогда нарушается порядок. Можно конечно такой запихнуть

2024-07-16 20:38 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dto/UpdateFilmRequest.java
> +public class UpdateFilmRequest {
Сделал аннотации

2024-07-16 20:40 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dto/UpdateUserRequest.java
> +    private Long id;
для id не буду делать потому что он должен быть в url это костыль потому что postman тесты его передают внутрь боди

2024-07-16 20:41 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        removeGenreDuplicates(film);
исправил

2024-07-16 20:41 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/mappers/FilmMapper.java
> +    FilmDto toFilmDto(Film film);
исправил

2024-07-16 20:41 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
удалил

2024-07-16 20:43 UTC, desyatov-student commented
Картинка со схемой лежит в мастере. Она была в прошлом задании я ее залил.
Каких тестов добавить больше ?

2024-07-17 09:55 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            ARRAY_AGG(DISTINCT g.ID) AS genre_ids,
как рекомендация можно сделать следующим образом
получаем фильмы без жанров, после чего отдельным методом получаем filmid, genreId, genreName по списку идентификаторов фильмов проходим по результату и добавляем нужные жанры в нужные фильмы

Вариант два, если сделать запрос с join получим кучу лишних строк, и их сгруппировать при маппинге в модель

2024-07-17 10:20 UTC, TomattmanYandex requested changes
Привет, добавил еще комментариев ответил на старые
новые аннотации выглядят хорошо, но многие из них дублируют существующиее
на одно поле можно повесить сразу неколько например вместо
ValidDescriptionAndNotBlank можно просто на поле повесить сразу  NotBlank и Size
также есть готовая аннотация для валидирования email и валидирования по паттерну
стоит удалить лишние
по поводу жанров в фильмах смотри сам, я готов принять и так как есть, но если переделаешь, будет лучше, за счет отсутствия вероятности ошибки

все еще не хватает схемы базы 
- в проекте должны быть картинка схемы бд
- в файле `README.md` должна быть ссылка на файл диаграммы.
(это текст из критериев проверки)

ну и дополнительный момент я писал в прошлой итерации, напишу в этой
хорошо бы добавить больше тестов

2024-07-17 10:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dto/NewFilmRequest.java
> +    @ValidDescriptionAndNotBlank
зачем нужна эта аннотация, если на одно поле можно сразу повесить две аннотации?
@NotBlank
@Size

2024-07-17 10:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dto/UpdateUserRequest.java
> +    private Long id;
это был коммент про валидацию)))

2024-07-17 10:20 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@JdbcTest
если хочешь проверить запрос в базу данных (по сути это тест хранилища) то стоит добавить класс UserDbStorageTest И добавить в него тесты для конкретно этого хранилища
ну и конечно же стоит добавить больше тестов
и еще момент, интеграционные тесты, это тесты которые тестирую взаимодействие различных компонентов, т.е. послали запрос на контроллер, а потом черз хранилище проверили что обьект изменился в базе (по условию вам надо было интеграционные тесты добавить)

2024-07-17 20:18 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dto/NewFilmRequest.java
> +    @ValidDescriptionAndNotBlank
Потому-что есть аннотация ValidDescriptionOrNull

В ней такая конструкция
@Null
@ValidDescriptionAndNotBlank
через OR

и если делать так через OR:

@Null
@notblank
@SiZe

Работать НЕ будет. 
Должно быть так:  (@Null OR (@Notblank AND @SiZe) )
В аннотации нельзя сделать сложные логические выражения

Это так же относится и к остальным аннотация(NotBlankOrNull, PastOrNull и др) ПОЭТОМУ они вроде как дублируются но на самом деле такая задумка.

2024-07-17 20:22 UTC, desyatov-student commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@JdbcTest
В здание был такой пример и что нужно тестировать методы БД:

> Теперь можно написать интеграционные тесты для DAO-объектов приложения по примеру выше. С помощью них вы проверите, правильно ли работают ваши запросы к базе данных. Убедитесь, что все публичные методы хранилища покрыты тестами. 

Если нужно что-то другое ну ок можно обсудить. В задание про другое.

2024-07-17 20:24 UTC, desyatov-student commented
Еще раз продублирую ответ по схемы БД:
**Картинка со схемой лежит в мастере. Она была в прошлом задании я ее залил.**

2024-07-17 20:25 UTC, desyatov-student commented
Вот скрин из основной ветки:
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/55a63db2-b93e-4252-b7a8-3dda5b7cfabd">

2024-07-17 20:37 UTC, desyatov-student commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmDbStorage.java
> +            ARRAY_AGG(DISTINCT g.ID) AS genre_ids,
1. Получается что будем бегать по массиву и соединять эти данные это сложность алгоритма будет O(n*k) 
2. тут я не совсем понял. Надо бы пример SQL. В других БД это решалось бы очень просто можно было в запросе завернуть сразу в объект но в этой базе все как урезано

2024-07-17 20:39 UTC, desyatov-student commented
Тесты я докину нужно договорится по текущим коментам

2024-07-18 07:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dto/NewFilmRequest.java
> +    @ValidDescriptionAndNotBlank
да, но это не объясняет зачем нужна именно эта аннотация, только для консистентности?

2024-07-18 08:00 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@JdbcTest
к самому тесту вопрсов особо нету, вопрос к тому, что если тест пишется в хранилищую юезров, то он должен иметь соответствующее расположение и имя, для того чтобы каши не было

2024-07-18 08:02 UTC, TomattmanYandex approved these changes
По тестам у вас будет в следующем спринте полноценное задание, если я не ошибаюсь, там можно будет с ними все сделать, а тут все что осталось - всякие мелочи, которые можно считать придирками
Принято

2024-07-20 09:10 UTC, merged